name: Deploy preview site from dev branch

on:
  push:
    branches:
      - dev

permissions:
  contents: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages /preview
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src
          destination_dir: preview   
          publish_branch: gh-pages
